using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace McF.Contracts
{
    public class COTData : DialyData
    {
        public string As_of_Date_In_Form_YYMMDD { get; set; }
        public double CFTC_Contract_Market_Code { get; set; }
        public string CFTC_Market_Code { get; set; }
        public double CFTC_Region_Code { get; set; }
        public double CFTC_Commodity_Code { get; set; }
        public double Open_Interest_All { get; set; }
        public double Prod_Merc_Positions_Long_ALL { get; set; }
        public double Prod_Merc_Positions_Short_ALL { get; set; }
        public double Swap_Positions_Long_All { get; set; }
        public double Swap__Positions_Short_All { get; set; }
        public double Swap__Positions_Spread_All { get; set; }
        public double M_Money_Positions_Long_ALL { get; set; }
        public double M_Money_Positions_Short_ALL { get; set; }
        public double M_Money_Positions_Spread_ALL { get; set; }
        public double Other_Rept_Positions_Long_ALL { get; set; }
        public double Other_Rept_Positions_Short_ALL { get; set; }
        public double Other_Rept_Positions_Spread_ALL { get; set; }
        public double Tot_Rept_Positions_Long_All { get; set; }
        public double Tot_Rept_Positions_Short_All { get; set; }
        public double NonRept_Positions_Long_All { get; set; }
        public double NonRept_Positions_Short_All { get; set; }
        public double Open_Interest_Old { get; set; }
        public double Prod_Merc_Positions_Long_Old { get; set; }
        public double Prod_Merc_Positions_Short_Old { get; set; }
        public double Swap_Positions_Long_Old { get; set; }
        public double Swap_Positions_Short_Old { get; set; }
        public double Swap_Positions_Spread_Old { get; set; }
        public double M_Money_Positions_Long_Old { get; set; }
        public double M_Money_Positions_Short_Old { get; set; }
        public double M_Money_Positions_Spread_Old { get; set; }
        public double Other_Rept_Positions_Long_Old { get; set; }
        public double Other_Rept_Positions_Short_Old { get; set; }
        public double Other_Rept_Positions_Spread_Old { get; set; }
        public double Tot_Rept_Positions_Long_Old { get; set; }
        public double Tot_Rept_Positions_Short_Old { get; set; }
        public double NonRept_Positions_Long_Old { get; set; }
        public double NonRept_Positions_Short_Old { get; set; }
        public double Open_Interest_Other { get; set; }
        public double Prod_Merc_Positions_Long_Other { get; set; }
        public double Prod_Merc_Positions_Short_Other { get; set; }
        public double Swap_Positions_Long_Other { get; set; }
        public double Swap_Positions_Short_Other { get; set; }
        public double Swap_Positions_Spread_Other { get; set; }
        public double M_Money_Positions_Long_Other { get; set; }
        public double M_Money_Positions_Short_Other { get; set; }
        public double M_Money_Positions_Spread_Other { get; set; }
        public double Other_Rept_Positions_Long_Other { get; set; }
        public double Other_Rept_Positions_Short_Other { get; set; }
        public double Other_Rept_Positions_Spread_Othr { get; set; }
        public double Tot_Rept_Positions_Long_Other { get; set; }
        public double Tot_Rept_Positions_Short_Other { get; set; }
        public double NonRept_Positions_Long_Other { get; set; }
        public double NonRept_Positions_Short_Other { get; set; }
        public double Change_in_Open_Interest_All { get; set; }
        public double Change_in_Prod_Merc_Long_All { get; set; }
        public double Change_in_Prod_Merc_Short_All { get; set; }
        public double Change_in_Swap_Long_All { get; set; }
        public double Change_in_Swap_Short_All { get; set; }
        public double Change_in_Swap_Spread_All { get; set; }
        public double Change_in_M_Money_Long_All { get; set; }
        public double Change_in_M_Money_Short_All { get; set; }
        public double Change_in_M_Money_Spread_All { get; set; }
        public double Change_in_Other_Rept_Long_All { get; set; }
        public double Change_in_Other_Rept_Short_All { get; set; }
        public double Change_in_Other_Rept_Spread_All { get; set; }
        public double Change_in_Tot_Rept_Long_All { get; set; }
        public double Change_in_Tot_Rept_Short_All { get; set; }
        public double Change_in_NonRept_Long_All { get; set; }
        public double Change_in_NonRept_Short_All { get; set; }
        public double Pct_of_Open_Interest_All { get; set; }
        public double Pct_of_OI_Prod_Merc_Long_All { get; set; }
        public double Pct_of_OI_Prod_Merc_Short_All { get; set; }
        public double Pct_of_OI_Swap_Long_All { get; set; }
        public double Pct_of_OI_Swap_Short_All { get; set; }
        public double Pct_of_OI_Swap_Spread_All { get; set; }
        public double Pct_of_OI_M_Money_Long_All { get; set; }
        public double Pct_of_OI_M_Money_Short_All { get; set; }
        public double Pct_of_OI_M_Money_Spread_All { get; set; }
        public double Pct_of_OI_Other_Rept_Long_All { get; set; }
        public double Pct_of_OI_Other_Rept_Short_All { get; set; }
        public double Pct_of_OI_Other_Rept_Spread_All { get; set; }
        public double Pct_of_OI_Tot_Rept_Long_All { get; set; }
        public double Pct_of_OI_Tot_Rept_Short_All { get; set; }
        public double Pct_of_OI_NonRept_Long_All { get; set; }
        public double Pct_of_OI_NonRept_Short_All { get; set; }
        public double Pct_of_Open_Interest_Old { get; set; }
        public double Pct_of_OI_Prod_Merc_Long_Old { get; set; }
        public double Pct_of_OI_Prod_Merc_Short_Old { get; set; }
        public double Pct_of_OI_Swap_Long_Old { get; set; }
        public double Pct_of_OI_Swap_Short_Old { get; set; }
        public double Pct_of_OI_Swap_Spread_Old { get; set; }
        public double Pct_of_OI_M_Money_Long_Old { get; set; }
        public double Pct_of_OI_M_Money_Short_Old { get; set; }
        public double Pct_of_OI_M_Money_Spread_Old { get; set; }
        public double Pct_of_OI_Other_Rept_Long_Old { get; set; }
        public double Pct_of_OI_Other_Rept_Short_Old { get; set; }
        public double Pct_of_OI_Other_Rept_Spread_Old { get; set; }
        public double Pct_of_OI_Tot_Rept_Long_Old { get; set; }
        public double Pct_of_OI_Tot_Rept_Short_Old { get; set; }
        public double Pct_of_OI_NonRept_Long_Old { get; set; }
        public double Pct_of_OI_NonRept_Short_Old { get; set; }
        public double Pct_of_Open_Interest_Other { get; set; }
        public double Pct_of_OI_Prod_Merc_Long_Other { get; set; }
        public double Pct_of_OI_Prod_Merc_Short_Other { get; set; }
        public double Pct_of_OI_Swap_Long_Other { get; set; }
        public double Pct_of_OI_Swap_Short_Other { get; set; }
        public double Pct_of_OI_Swap_Spread_Other { get; set; }
        public double Pct_of_OI_M_Money_Long_Other { get; set; }
        public double Pct_of_OI_M_Money_Short_Other { get; set; }
        public double Pct_of_OI_M_Money_Spread_Other { get; set; }
        public double Pct_of_OI_Other_Rept_Long_Other { get; set; }
        public double Pct_of_OI_Other_Rept_Short_Other { get; set; }
        public double Pct_of_OI_Other_Rept_Spread_Othr { get; set; }
        public double Pct_of_OI_Tot_Rept_Long_Other { get; set; }
        public double Pct_of_OI_Tot_Rept_Short_Other { get; set; }
        public double Pct_of_OI_NonRept_Long_Other { get; set; }
        public double Pct_of_OI_NonRept_Short_Other { get; set; }
        public double Traders_Tot_All { get; set; }
        public double Traders_Prod_Merc_Long_All { get; set; }
        public double Traders_Prod_Merc_Short_All { get; set; }
        public double Traders_Swap_Long_All { get; set; }
        public double Traders_Swap_Short_All { get; set; }
        public double Traders_Swap_Spread_All { get; set; }
        public double Traders_M_Money_Long_All { get; set; }
        public double Traders_M_Money_Short_All { get; set; }
        public double Traders_M_Money_Spread_All { get; set; }
        public double Traders_Other_Rept_Long_All { get; set; }
        public double Traders_Other_Rept_Short_All { get; set; }
        public double Traders_Other_Rept_Spread_All { get; set; }
        public double Traders_Tot_Rept_Long_All { get; set; }
        public double Traders_Tot_Rept_Short_All { get; set; }
        public double Traders_Tot_Old { get; set; }
        public double Traders_Prod_Merc_Long_Old { get; set; }
        public double Traders_Prod_Merc_Short_Old { get; set; }
        public double Traders_Swap_Long_Old { get; set; }
        public double Traders_Swap_Short_Old { get; set; }
        public double Traders_Swap_Spread_Old { get; set; }
        public double Traders_M_Money_Long_Old { get; set; }
        public double Traders_M_Money_Short_Old { get; set; }
        public double Traders_M_Money_Spread_Old { get; set; }
        public double Traders_Other_Rept_Long_Old { get; set; }
        public double Traders_Other_Rept_Short_Old { get; set; }
        public double Traders_Other_Rept_Spread_Old { get; set; }
        public double Traders_Tot_Rept_Long_Old { get; set; }
        public double Traders_Tot_Rept_Short_Old { get; set; }
        public double Traders_Tot_Other { get; set; }
        public double Traders_Prod_Merc_Long_Other { get; set; }
        public double Traders_Prod_Merc_Short_Other { get; set; }
        public double Traders_Swap_Long_Other { get; set; }
        public double Traders_Swap_Short_Other { get; set; }
        public double Traders_Swap_Spread_Other { get; set; }
        public double Traders_M_Money_Long_Other { get; set; }
        public double Traders_M_Money_Short_Other { get; set; }
        public double Traders_M_Money_Spread_Other { get; set; }
        public double Traders_Other_Rept_Long_Other { get; set; }
        public double Traders_Other_Rept_Short_Other { get; set; }
        public double Traders_Other_Rept_Spread_Other { get; set; }
        public double Traders_Tot_Rept_Long_Other { get; set; }
        public double Traders_Tot_Rept_Short_Other { get; set; }
        public double Conc_Gross_LE_4_TDR_Long_All { get; set; }
        public double Conc_Gross_LE_4_TDR_Short_All { get; set; }
        public double Conc_Gross_LE_8_TDR_Long_All { get; set; }
        public double Conc_Gross_LE_8_TDR_Short_All { get; set; }
        public double Conc_Net_LE_4_TDR_Long_All { get; set; }
        public double Conc_Net_LE_4_TDR_Short_All { get; set; }
        public double Conc_Net_LE_8_TDR_Long_All { get; set; }
        public double Conc_Net_LE_8_TDR_Short_All { get; set; }
        public double Conc_Gross_LE_4_TDR_Long_Old { get; set; }
        public double Conc_Gross_LE_4_TDR_Short_Old { get; set; }
        public double Conc_Gross_LE_8_TDR_Long_Old { get; set; }
        public double Conc_Gross_LE_8_TDR_Short_Old { get; set; }
        public double Conc_Net_LE_4_TDR_Long_Old { get; set; }
        public double Conc_Net_LE_4_TDR_Short_Old { get; set; }
        public double Conc_Net_LE_8_TDR_Long_Old { get; set; }
        public double Conc_Net_LE_8_TDR_Short_Old { get; set; }
        public double Conc_Gross_LE_4_TDR_Long_Other { get; set; }
        public double Conc_Gross_LE_4_TDR_Short_Other { get; set; }
        public double Conc_Gross_LE_8_TDR_Long_Other { get; set; }
        public double Conc_Gross_LE_8_TDR_Short_Other { get; set; }
        public double Conc_Net_LE_4_TDR_Long_Other { get; set; }
        public double Conc_Net_LE_4_TDR_Short_Other { get; set; }
        public double Conc_Net_LE_8_TDR_Long_Other { get; set; }
        public double Conc_Net_LE_8_TDR_Short_Other { get; set; }
        public string Contract_Units { get; set; }
        public string CFTC_SubGroup_Code { get; set; }
        public string FutOnly_or_Combined { get; set; }
    }
}
