//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://pxweb.dtn.telvent.com", ClrNamespace = "pxweb.dtn.telvent.com")]

namespace pxweb.dtn.telvent.com
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BaseDto", Namespace = "http://pxweb.dtn.telvent.com")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.BaseUserDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.BaseCalculatorDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.CrackCalculatorDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.CrushCalculatorDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetHistoryCorrectionsDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetNewsIndexDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetNewsStoryDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.FindSymbolDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetAccountStatusDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetAccountRequestsDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.BaseMarketVendorDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.BaseIntervalLimitDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetDailyHistoryDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetMinuteHistoryDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetTickHistoryDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetForwardCurveDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetQuoteSnapDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetOptionGreeksDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetMarketScansDto))]
    public partial class BaseDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BaseUserDto", Namespace = "http://pxweb.dtn.telvent.com")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.BaseCalculatorDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.CrackCalculatorDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.CrushCalculatorDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetHistoryCorrectionsDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetNewsIndexDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetNewsStoryDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.FindSymbolDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetAccountStatusDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetAccountRequestsDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.BaseMarketVendorDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.BaseIntervalLimitDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetDailyHistoryDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetMinuteHistoryDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetTickHistoryDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetForwardCurveDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetQuoteSnapDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetOptionGreeksDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetMarketScansDto))]
    public partial class BaseUserDto : pxweb.dtn.telvent.com.BaseDto
    {

        private string FormatField;

        private string PasswordField;

        private string UserIDField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Format
        {
            get
            {
                return this.FormatField;
            }
            set
            {
                this.FormatField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BaseCalculatorDto", Namespace = "http://pxweb.dtn.telvent.com")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.CrackCalculatorDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.CrushCalculatorDto))]
    public partial class BaseCalculatorDto : pxweb.dtn.telvent.com.BaseUserDto
    {

        private string NumMonthsField;

        private string PriceFieldField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumMonths
        {
            get
            {
                return this.NumMonthsField;
            }
            set
            {
                this.NumMonthsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceField
        {
            get
            {
                return this.PriceFieldField;
            }
            set
            {
                this.PriceFieldField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CrackCalculatorDto", Namespace = "http://pxweb.dtn.telvent.com")]
    public partial class CrackCalculatorDto : pxweb.dtn.telvent.com.BaseCalculatorDto
    {

        private string CrudeRootField;

        private string GasRootField;

        private string HeatingOilRootField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrudeRoot
        {
            get
            {
                return this.CrudeRootField;
            }
            set
            {
                this.CrudeRootField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GasRoot
        {
            get
            {
                return this.GasRootField;
            }
            set
            {
                this.GasRootField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeatingOilRoot
        {
            get
            {
                return this.HeatingOilRootField;
            }
            set
            {
                this.HeatingOilRootField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CrushCalculatorDto", Namespace = "http://pxweb.dtn.telvent.com")]
    public partial class CrushCalculatorDto : pxweb.dtn.telvent.com.BaseCalculatorDto
    {

        private string BeanOilRootField;

        private string SoyMealRootField;

        private string SoyRootField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeanOilRoot
        {
            get
            {
                return this.BeanOilRootField;
            }
            set
            {
                this.BeanOilRootField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoyMealRoot
        {
            get
            {
                return this.SoyMealRootField;
            }
            set
            {
                this.SoyMealRootField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoyRoot
        {
            get
            {
                return this.SoyRootField;
            }
            set
            {
                this.SoyRootField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetHistoryCorrectionsDto", Namespace = "http://pxweb.dtn.telvent.com")]
    public partial class GetHistoryCorrectionsDto : pxweb.dtn.telvent.com.BaseUserDto
    {

        private string EndTimeField;

        private string MarketField;

        private string StartTimeField;

        private string SymbolField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Market
        {
            get
            {
                return this.MarketField;
            }
            set
            {
                this.MarketField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol
        {
            get
            {
                return this.SymbolField;
            }
            set
            {
                this.SymbolField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetNewsIndexDto", Namespace = "http://pxweb.dtn.telvent.com")]
    public partial class GetNewsIndexDto : pxweb.dtn.telvent.com.BaseUserDto
    {

        private string FilterField;

        private string LimitField;

        private string TZOffsetField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filter
        {
            get
            {
                return this.FilterField;
            }
            set
            {
                this.FilterField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Limit
        {
            get
            {
                return this.LimitField;
            }
            set
            {
                this.LimitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TZOffset
        {
            get
            {
                return this.TZOffsetField;
            }
            set
            {
                this.TZOffsetField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetNewsStoryDto", Namespace = "http://pxweb.dtn.telvent.com")]
    public partial class GetNewsStoryDto : pxweb.dtn.telvent.com.BaseUserDto
    {

        private string KeyField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "FindSymbolDto", Namespace = "http://pxweb.dtn.telvent.com")]
    public partial class FindSymbolDto : pxweb.dtn.telvent.com.BaseUserDto
    {

        private string CategoryField;

        private string LimitField;

        private string SearchStringField;

        private string SearchTypeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Limit
        {
            get
            {
                return this.LimitField;
            }
            set
            {
                this.LimitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchString
        {
            get
            {
                return this.SearchStringField;
            }
            set
            {
                this.SearchStringField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchType
        {
            get
            {
                return this.SearchTypeField;
            }
            set
            {
                this.SearchTypeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetAccountStatusDto", Namespace = "http://pxweb.dtn.telvent.com")]
    public partial class GetAccountStatusDto : pxweb.dtn.telvent.com.BaseUserDto
    {

        private string GroupField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetAccountRequestsDto", Namespace = "http://pxweb.dtn.telvent.com")]
    public partial class GetAccountRequestsDto : pxweb.dtn.telvent.com.BaseUserDto
    {

        private string PeriodsField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Periods
        {
            get
            {
                return this.PeriodsField;
            }
            set
            {
                this.PeriodsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BaseMarketVendorDto", Namespace = "http://pxweb.dtn.telvent.com")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.BaseIntervalLimitDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetDailyHistoryDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetMinuteHistoryDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetTickHistoryDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetForwardCurveDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetQuoteSnapDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetOptionGreeksDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetMarketScansDto))]
    public partial class BaseMarketVendorDto : pxweb.dtn.telvent.com.BaseUserDto
    {

        private string MarketField;

        private string VendorField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Market
        {
            get
            {
                return this.MarketField;
            }
            set
            {
                this.MarketField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vendor
        {
            get
            {
                return this.VendorField;
            }
            set
            {
                this.VendorField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BaseIntervalLimitDto", Namespace = "http://pxweb.dtn.telvent.com")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetDailyHistoryDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetMinuteHistoryDto))]
    public partial class BaseIntervalLimitDto : pxweb.dtn.telvent.com.BaseMarketVendorDto
    {

        private string IntervalField;

        private string LimitField;

        private string SymbolField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Interval
        {
            get
            {
                return this.IntervalField;
            }
            set
            {
                this.IntervalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Limit
        {
            get
            {
                return this.LimitField;
            }
            set
            {
                this.LimitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol
        {
            get
            {
                return this.SymbolField;
            }
            set
            {
                this.SymbolField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetDailyHistoryDto", Namespace = "http://pxweb.dtn.telvent.com")]
    public partial class GetDailyHistoryDto : pxweb.dtn.telvent.com.BaseIntervalLimitDto
    {

        private string EndDateField;

        private string StartDateField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetMinuteHistoryDto", Namespace = "http://pxweb.dtn.telvent.com")]
    public partial class GetMinuteHistoryDto : pxweb.dtn.telvent.com.BaseIntervalLimitDto
    {

        private string EndTimeField;

        private string StartTimeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetTickHistoryDto", Namespace = "http://pxweb.dtn.telvent.com")]
    public partial class GetTickHistoryDto : pxweb.dtn.telvent.com.BaseMarketVendorDto
    {

        private string EndTimeField;

        private string FilterField;

        private string LimitField;

        private string StartTimeField;

        private string SymbolField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filter
        {
            get
            {
                return this.FilterField;
            }
            set
            {
                this.FilterField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Limit
        {
            get
            {
                return this.LimitField;
            }
            set
            {
                this.LimitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol
        {
            get
            {
                return this.SymbolField;
            }
            set
            {
                this.SymbolField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetForwardCurveDto", Namespace = "http://pxweb.dtn.telvent.com")]
    public partial class GetForwardCurveDto : pxweb.dtn.telvent.com.BaseMarketVendorDto
    {

        private string CurveDateField;

        private string LimitField;

        private string RootField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurveDate
        {
            get
            {
                return this.CurveDateField;
            }
            set
            {
                this.CurveDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Limit
        {
            get
            {
                return this.LimitField;
            }
            set
            {
                this.LimitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Root
        {
            get
            {
                return this.RootField;
            }
            set
            {
                this.RootField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetQuoteSnapDto", Namespace = "http://pxweb.dtn.telvent.com")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetOptionGreeksDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pxweb.dtn.telvent.com.GetMarketScansDto))]
    public partial class GetQuoteSnapDto : pxweb.dtn.telvent.com.BaseMarketVendorDto
    {

        private string SymbolField;

        private string TypeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol
        {
            get
            {
                return this.SymbolField;
            }
            set
            {
                this.SymbolField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetOptionGreeksDto", Namespace = "http://pxweb.dtn.telvent.com")]
    public partial class GetOptionGreeksDto : pxweb.dtn.telvent.com.GetQuoteSnapDto
    {

        private string BasisField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Basis
        {
            get
            {
                return this.BasisField;
            }
            set
            {
                this.BasisField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetMarketScansDto", Namespace = "http://pxweb.dtn.telvent.com")]
    public partial class GetMarketScansDto : pxweb.dtn.telvent.com.GetQuoteSnapDto
    {

        private string LimitField;

        private string ReportField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Limit
        {
            get
            {
                return this.LimitField;
            }
            set
            {
                this.LimitField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Report
        {
            get
            {
                return this.ReportField;
            }
            set
            {
                this.ReportField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://pxweb.dtn.telvent.com", ConfigurationName = "IPXServiceDto")]
public interface IPXServiceDto
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetQuoteSnap", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetQuoteSnapResponse")]
    string GetQuoteSnap(pxweb.dtn.telvent.com.GetQuoteSnapDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetQuoteSnap", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetQuoteSnapResponse")]
    System.Threading.Tasks.Task<string> GetQuoteSnapAsync(pxweb.dtn.telvent.com.GetQuoteSnapDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetOptionGreeks", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetOptionGreeksResponse")]
    string GetOptionGreeks(pxweb.dtn.telvent.com.GetOptionGreeksDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetOptionGreeks", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetOptionGreeksResponse")]
    System.Threading.Tasks.Task<string> GetOptionGreeksAsync(pxweb.dtn.telvent.com.GetOptionGreeksDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetMarketScans", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetMarketScansResponse")]
    string GetMarketScans(pxweb.dtn.telvent.com.GetMarketScansDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetMarketScans", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetMarketScansResponse")]
    System.Threading.Tasks.Task<string> GetMarketScansAsync(pxweb.dtn.telvent.com.GetMarketScansDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/CrackCalculator", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/CrackCalculatorResponse")]
    string CrackCalculator(pxweb.dtn.telvent.com.CrackCalculatorDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/CrackCalculator", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/CrackCalculatorResponse")]
    System.Threading.Tasks.Task<string> CrackCalculatorAsync(pxweb.dtn.telvent.com.CrackCalculatorDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/CrushCalculator", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/CrushCalculatorResponse")]
    string CrushCalculator(pxweb.dtn.telvent.com.CrushCalculatorDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/CrushCalculator", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/CrushCalculatorResponse")]
    System.Threading.Tasks.Task<string> CrushCalculatorAsync(pxweb.dtn.telvent.com.CrushCalculatorDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetDailyHistory", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetDailyHistoryResponse")]
    string GetDailyHistory(pxweb.dtn.telvent.com.GetDailyHistoryDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetDailyHistory", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetDailyHistoryResponse")]
    System.Threading.Tasks.Task<string> GetDailyHistoryAsync(pxweb.dtn.telvent.com.GetDailyHistoryDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetMinuteHistory", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetMinuteHistoryResponse")]
    string GetMinuteHistory(pxweb.dtn.telvent.com.GetMinuteHistoryDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetMinuteHistory", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetMinuteHistoryResponse")]
    System.Threading.Tasks.Task<string> GetMinuteHistoryAsync(pxweb.dtn.telvent.com.GetMinuteHistoryDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetTickHistory", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetTickHistoryResponse")]
    string GetTickHistory(pxweb.dtn.telvent.com.GetTickHistoryDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetTickHistory", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetTickHistoryResponse")]
    System.Threading.Tasks.Task<string> GetTickHistoryAsync(pxweb.dtn.telvent.com.GetTickHistoryDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetForwardCurve", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetForwardCurveResponse")]
    string GetForwardCurve(pxweb.dtn.telvent.com.GetForwardCurveDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetForwardCurve", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetForwardCurveResponse")]
    System.Threading.Tasks.Task<string> GetForwardCurveAsync(pxweb.dtn.telvent.com.GetForwardCurveDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetHistoryCorrections", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetHistoryCorrectionsResponse")]
    string GetHistoryCorrections(pxweb.dtn.telvent.com.GetHistoryCorrectionsDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetHistoryCorrections", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetHistoryCorrectionsResponse")]
    System.Threading.Tasks.Task<string> GetHistoryCorrectionsAsync(pxweb.dtn.telvent.com.GetHistoryCorrectionsDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetNewsIndex", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetNewsIndexResponse")]
    string GetNewsIndex(pxweb.dtn.telvent.com.GetNewsIndexDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetNewsIndex", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetNewsIndexResponse")]
    System.Threading.Tasks.Task<string> GetNewsIndexAsync(pxweb.dtn.telvent.com.GetNewsIndexDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetNewsStory", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetNewsStoryResponse")]
    string GetNewsStory(pxweb.dtn.telvent.com.GetNewsStoryDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetNewsStory", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetNewsStoryResponse")]
    System.Threading.Tasks.Task<string> GetNewsStoryAsync(pxweb.dtn.telvent.com.GetNewsStoryDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/FindSymbol", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/FindSymbolResponse")]
    string FindSymbol(pxweb.dtn.telvent.com.FindSymbolDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/FindSymbol", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/FindSymbolResponse")]
    System.Threading.Tasks.Task<string> FindSymbolAsync(pxweb.dtn.telvent.com.FindSymbolDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetAccountStatus", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetAccountStatusResponse")]
    string GetAccountStatus(pxweb.dtn.telvent.com.GetAccountStatusDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetAccountStatus", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetAccountStatusResponse")]
    System.Threading.Tasks.Task<string> GetAccountStatusAsync(pxweb.dtn.telvent.com.GetAccountStatusDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetAccountRequests", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetAccountRequestsResponse")]
    string GetAccountRequests(pxweb.dtn.telvent.com.GetAccountRequestsDto request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetAccountRequests", ReplyAction = "http://pxweb.dtn.telvent.com/IPXServiceDto/GetAccountRequestsResponse")]
    System.Threading.Tasks.Task<string> GetAccountRequestsAsync(pxweb.dtn.telvent.com.GetAccountRequestsDto request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IPXServiceDtoChannel : IPXServiceDto, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class PXServiceDtoClient : System.ServiceModel.ClientBase<IPXServiceDto>, IPXServiceDto
{

    public PXServiceDtoClient()
    {
    }

    public PXServiceDtoClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public PXServiceDtoClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public PXServiceDtoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public PXServiceDtoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public string GetQuoteSnap(pxweb.dtn.telvent.com.GetQuoteSnapDto request)
    {
        return base.Channel.GetQuoteSnap(request);
    }

    public System.Threading.Tasks.Task<string> GetQuoteSnapAsync(pxweb.dtn.telvent.com.GetQuoteSnapDto request)
    {
        return base.Channel.GetQuoteSnapAsync(request);
    }

    public string GetOptionGreeks(pxweb.dtn.telvent.com.GetOptionGreeksDto request)
    {
        return base.Channel.GetOptionGreeks(request);
    }

    public System.Threading.Tasks.Task<string> GetOptionGreeksAsync(pxweb.dtn.telvent.com.GetOptionGreeksDto request)
    {
        return base.Channel.GetOptionGreeksAsync(request);
    }

    public string GetMarketScans(pxweb.dtn.telvent.com.GetMarketScansDto request)
    {
        return base.Channel.GetMarketScans(request);
    }

    public System.Threading.Tasks.Task<string> GetMarketScansAsync(pxweb.dtn.telvent.com.GetMarketScansDto request)
    {
        return base.Channel.GetMarketScansAsync(request);
    }

    public string CrackCalculator(pxweb.dtn.telvent.com.CrackCalculatorDto request)
    {
        return base.Channel.CrackCalculator(request);
    }

    public System.Threading.Tasks.Task<string> CrackCalculatorAsync(pxweb.dtn.telvent.com.CrackCalculatorDto request)
    {
        return base.Channel.CrackCalculatorAsync(request);
    }

    public string CrushCalculator(pxweb.dtn.telvent.com.CrushCalculatorDto request)
    {
        return base.Channel.CrushCalculator(request);
    }

    public System.Threading.Tasks.Task<string> CrushCalculatorAsync(pxweb.dtn.telvent.com.CrushCalculatorDto request)
    {
        return base.Channel.CrushCalculatorAsync(request);
    }

    public string GetDailyHistory(pxweb.dtn.telvent.com.GetDailyHistoryDto request)
    {
        return base.Channel.GetDailyHistory(request);
    }

    public System.Threading.Tasks.Task<string> GetDailyHistoryAsync(pxweb.dtn.telvent.com.GetDailyHistoryDto request)
    {
        return base.Channel.GetDailyHistoryAsync(request);
    }

    public string GetMinuteHistory(pxweb.dtn.telvent.com.GetMinuteHistoryDto request)
    {
        return base.Channel.GetMinuteHistory(request);
    }

    public System.Threading.Tasks.Task<string> GetMinuteHistoryAsync(pxweb.dtn.telvent.com.GetMinuteHistoryDto request)
    {
        return base.Channel.GetMinuteHistoryAsync(request);
    }

    public string GetTickHistory(pxweb.dtn.telvent.com.GetTickHistoryDto request)
    {
        return base.Channel.GetTickHistory(request);
    }

    public System.Threading.Tasks.Task<string> GetTickHistoryAsync(pxweb.dtn.telvent.com.GetTickHistoryDto request)
    {
        return base.Channel.GetTickHistoryAsync(request);
    }

    public string GetForwardCurve(pxweb.dtn.telvent.com.GetForwardCurveDto request)
    {
        return base.Channel.GetForwardCurve(request);
    }

    public System.Threading.Tasks.Task<string> GetForwardCurveAsync(pxweb.dtn.telvent.com.GetForwardCurveDto request)
    {
        return base.Channel.GetForwardCurveAsync(request);
    }

    public string GetHistoryCorrections(pxweb.dtn.telvent.com.GetHistoryCorrectionsDto request)
    {
        return base.Channel.GetHistoryCorrections(request);
    }

    public System.Threading.Tasks.Task<string> GetHistoryCorrectionsAsync(pxweb.dtn.telvent.com.GetHistoryCorrectionsDto request)
    {
        return base.Channel.GetHistoryCorrectionsAsync(request);
    }

    public string GetNewsIndex(pxweb.dtn.telvent.com.GetNewsIndexDto request)
    {
        return base.Channel.GetNewsIndex(request);
    }

    public System.Threading.Tasks.Task<string> GetNewsIndexAsync(pxweb.dtn.telvent.com.GetNewsIndexDto request)
    {
        return base.Channel.GetNewsIndexAsync(request);
    }

    public string GetNewsStory(pxweb.dtn.telvent.com.GetNewsStoryDto request)
    {
        return base.Channel.GetNewsStory(request);
    }

    public System.Threading.Tasks.Task<string> GetNewsStoryAsync(pxweb.dtn.telvent.com.GetNewsStoryDto request)
    {
        return base.Channel.GetNewsStoryAsync(request);
    }

    public string FindSymbol(pxweb.dtn.telvent.com.FindSymbolDto request)
    {
        return base.Channel.FindSymbol(request);
    }

    public System.Threading.Tasks.Task<string> FindSymbolAsync(pxweb.dtn.telvent.com.FindSymbolDto request)
    {
        return base.Channel.FindSymbolAsync(request);
    }

    public string GetAccountStatus(pxweb.dtn.telvent.com.GetAccountStatusDto request)
    {
        return base.Channel.GetAccountStatus(request);
    }

    public System.Threading.Tasks.Task<string> GetAccountStatusAsync(pxweb.dtn.telvent.com.GetAccountStatusDto request)
    {
        return base.Channel.GetAccountStatusAsync(request);
    }

    public string GetAccountRequests(pxweb.dtn.telvent.com.GetAccountRequestsDto request)
    {
        return base.Channel.GetAccountRequests(request);
    }

    public System.Threading.Tasks.Task<string> GetAccountRequestsAsync(pxweb.dtn.telvent.com.GetAccountRequestsDto request)
    {
        return base.Channel.GetAccountRequestsAsync(request);
    }
}
